---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.3
  creationTimestamp: null
  name: vitessbackupstorages.planetscale.com
spec:
  group: planetscale.com
  names:
    kind: VitessBackupStorage
    listKind: VitessBackupStorageList
    plural: vitessbackupstorages
    shortNames:
    - vtbs
    singular: vitessbackupstorage
  scope: Namespaced
  versions:
  - name: v2
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              location:
                properties:
                  annotations:
                    additionalProperties:
                      type: string
                    type: object
                  azblob:
                    properties:
                      account:
                        minLength: 1
                        type: string
                      authSecret:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                          volumeName:
                            type: string
                        required:
                        - key
                        type: object
                      container:
                        minLength: 1
                        type: string
                      keyPrefix:
                        maxLength: 256
                        pattern: ^[^\r\n]*$
                        type: string
                    required:
                    - account
                    - authSecret
                    - container
                    type: object
                  ceph:
                    properties:
                      authSecret:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                          volumeName:
                            type: string
                        required:
                        - key
                        type: object
                    required:
                    - authSecret
                    type: object
                  gcs:
                    properties:
                      authSecret:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                          volumeName:
                            type: string
                        required:
                        - key
                        type: object
                      bucket:
                        minLength: 1
                        type: string
                      keyPrefix:
                        maxLength: 256
                        pattern: ^[^\r\n]*$
                        type: string
                    required:
                    - bucket
                    type: object
                  name:
                    maxLength: 63
                    pattern: ^[A-Za-z0-9]([A-Za-z0-9-_.]*[A-Za-z0-9])?$
                    type: string
                  s3:
                    properties:
                      authSecret:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                          volumeName:
                            type: string
                        required:
                        - key
                        type: object
                      bucket:
                        minLength: 1
                        type: string
                      endpoint:
                        type: string
                      forcePathStyle:
                        type: boolean
                      keyPrefix:
                        maxLength: 256
                        pattern: ^[^\r\n]*$
                        type: string
                      region:
                        minLength: 1
                        type: string
                    required:
                    - bucket
                    - region
                    type: object
                  volume:
                    x-kubernetes-preserve-unknown-fields: true
                  volumeSubPath:
                    type: string
                type: object
              subcontroller:
                properties:
                  serviceAccountName:
                    type: string
                type: object
            required:
            - location
            type: object
          status:
            properties:
              observedGeneration:
                format: int64
                type: integer
              totalBackupCount:
                format: int32
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
