apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vitessbackupstorages.planetscale.com
spec:
  group: planetscale.com
  names:
    kind: VitessBackupStorage
    listKind: VitessBackupStorageList
    plural: vitessbackupstorages
    shortNames:
    - vtbs
    singular: vitessbackupstorage
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            location:
              description: Location specifies the Vitess parameters for connecting
                to the backup storage location.
              properties:
                azblob:
                  description: Azblob specifies a backup location in Azure Blob ResourceChangesAllowed.
                  properties:
                    account:
                      description: Account is the name of the Azure storage account
                        to use.
                      minLength: 1
                      type: string
                    authSecret:
                      description: AuthSecret is a reference to the Secret to use
                        for Azure authentication.
                      properties:
                        key:
                          description: Key is the name of the item within the data
                            source to use as the value.  For a Kubernetes Secret object
                            (specified with the 'name' field), this is the key within
                            the 'data' map.  When 'volumeName' is used, this specifies
                            the name of the file to load within that Volume.
                          type: string
                        name:
                          description: Name is the name of a Kubernetes Secret object
                            to use as the data source. The Secret must be in the same
                            namespace as the VitessCluster.  The 'key' field defines
                            the item to pick from the Secret object's 'data' map.  If
                            a Secret name is not specified, the data source must be
                            defined with the 'volumeName' field instead.
                          type: string
                        volumeName:
                          description: VolumeName directly specifies the name of a
                            Volume in each Pod that should be mounted. You must ensure
                            a Volume by that name exists in all relevant Pods, such
                            as by using the appropriate ExtraVolumes fields. If specified,
                            this takes precedence over the 'name' field.  The 'key'
                            field defines the name of the file to load within this
                            Volume.
                          type: string
                      required:
                      - key
                      type: object
                    container:
                      description: Container is the name of the Azure storage account
                        container to use.
                      minLength: 1
                      type: string
                    keyPrefix:
                      description: KeyPrefix is an optional prefix added to all object
                        keys created by Vitess. This is only needed if the same container
                        is also used for something other than backups for VitessClusters.
                        Backups from different clusters, keyspaces, or shards will
                        automatically avoid colliding with each other within a container,
                        regardless of this setting.
                      maxLength: 256
                      pattern: ^[^\r\n]*$
                      type: string
                  required:
                  - account
                  - container
                  - authSecret
                  type: object
                gcs:
                  description: GCS specifies a backup location in Google Cloud ResourceChangesAllowed.
                  properties:
                    authSecret:
                      description: 'AuthSecret is a reference to the Secret to use
                        for GCS authentication. If set, this must point to a file
                        in the format expected for the GOOGLE_APPLICATION_CREDENTIALS
                        environment variable. Default: Use the default credentials
                        of the Node.'
                      properties:
                        key:
                          description: Key is the name of the item within the data
                            source to use as the value.  For a Kubernetes Secret object
                            (specified with the 'name' field), this is the key within
                            the 'data' map.  When 'volumeName' is used, this specifies
                            the name of the file to load within that Volume.
                          type: string
                        name:
                          description: Name is the name of a Kubernetes Secret object
                            to use as the data source. The Secret must be in the same
                            namespace as the VitessCluster.  The 'key' field defines
                            the item to pick from the Secret object's 'data' map.  If
                            a Secret name is not specified, the data source must be
                            defined with the 'volumeName' field instead.
                          type: string
                        volumeName:
                          description: VolumeName directly specifies the name of a
                            Volume in each Pod that should be mounted. You must ensure
                            a Volume by that name exists in all relevant Pods, such
                            as by using the appropriate ExtraVolumes fields. If specified,
                            this takes precedence over the 'name' field.  The 'key'
                            field defines the name of the file to load within this
                            Volume.
                          type: string
                      required:
                      - key
                      type: object
                    bucket:
                      description: Bucket is the name of the GCS bucket to use.
                      minLength: 1
                      type: string
                    keyPrefix:
                      description: KeyPrefix is an optional prefix added to all object
                        keys created by Vitess. This is only needed if the same bucket
                        is also used for something other than backups for VitessClusters.
                        Backups from different clusters, keyspaces, or shards will
                        automatically avoid colliding with each other within a bucket,
                        regardless of this setting.
                      maxLength: 256
                      pattern: ^[^\r\n]*$
                      type: string
                  required:
                  - bucket
                  type: object
                name:
                  description: Name is used to refer to this backup location from
                    other parts of a VitessCluster object, such as in tablet pool
                    definitions. This name must be unique among all backup locations
                    defined in a given cluster. A backup location with an empty name
                    defines the default location used when a tablet pool does not
                    specify a backup location name.
                  maxLength: 25
                  pattern: ^[a-z0-9]([a-z0-9]*[a-z0-9])?$
                  type: string
                s3:
                  description: S3 specifies a backup location in Amazon S3.
                  properties:
                    authSecret:
                      description: 'AuthSecret is a reference to the Secret to use
                        for S3 authentication. If set, this must point to a file in
                        the format expected for the `~/.aws/credentials` file. Default:
                        Use the default credentials of the Node.'
                      properties:
                        key:
                          description: Key is the name of the item within the data
                            source to use as the value.  For a Kubernetes Secret object
                            (specified with the 'name' field), this is the key within
                            the 'data' map.  When 'volumeName' is used, this specifies
                            the name of the file to load within that Volume.
                          type: string
                        name:
                          description: Name is the name of a Kubernetes Secret object
                            to use as the data source. The Secret must be in the same
                            namespace as the VitessCluster.  The 'key' field defines
                            the item to pick from the Secret object's 'data' map.  If
                            a Secret name is not specified, the data source must be
                            defined with the 'volumeName' field instead.
                          type: string
                        volumeName:
                          description: VolumeName directly specifies the name of a
                            Volume in each Pod that should be mounted. You must ensure
                            a Volume by that name exists in all relevant Pods, such
                            as by using the appropriate ExtraVolumes fields. If specified,
                            this takes precedence over the 'name' field.  The 'key'
                            field defines the name of the file to load within this
                            Volume.
                          type: string
                      required:
                      - key
                      type: object
                    bucket:
                      description: Bucket is the name of the S3 bucket to use.
                      minLength: 1
                      type: string
                    endpoint:
                      description: 'Endpoint is the `host:port` (port is required)
                        for the S3 backend. Default: Use the endpoint associated with
                        `region` by the driver.'
                      type: string
                    keyPrefix:
                      description: KeyPrefix is an optional prefix added to all object
                        keys created by Vitess. This is only needed if the same bucket
                        is also used for something other than backups for VitessClusters.
                        Backups from different clusters, keyspaces, or shards will
                        automatically avoid colliding with each other within a bucket,
                        regardless of this setting.
                      maxLength: 256
                      pattern: ^[^\r\n]*$
                      type: string
                    region:
                      description: Region is the AWS region in which the bucket is
                        located.
                      minLength: 1
                      type: string
                  required:
                  - region
                  - bucket
                  type: object
                volume:
                  description: Volume specifies a backup location as a Kubernetes
                    Volume Source to mount. This can be used, for example, to store
                    backups on an NFS mount, or on a shared host path for local testing.
                  type: object
              type: object
          required:
          - location
          type: object
        status:
          properties:
            observedGeneration:
              description: The generation observed by the controller.
              format: int64
              type: integer
            totalBackupCount:
              description: TotalBackupCount is the total number of backups found in
                this storage location, across all keyspaces and shards.
              format: int32
              type: integer
          type: object
  version: v2
  versions:
  - name: v2
    served: true
    storage: true
