resources:
- operator.yaml
- role_binding.yaml
- role.yaml
- service_account.yaml
- priority.yaml
- crds/planetscale.com_etcdlockservers_crd.yaml
- crds/planetscale.com_vitessbackups_crd.yaml
- crds/planetscale.com_vitessbackupstorages_crd.yaml
- crds/planetscale.com_vitesscells_crd.yaml
- crds/planetscale.com_vitessclusters_crd.yaml
- crds/planetscale.com_vitesskeyspaces_crd.yaml
- crds/planetscale.com_vitessshards_crd.yaml
